### ISSUE TITLE
npm start 会报错

### ISSUE THREAD

**Issue by zhangxu003** [duxianwei520/react#49]
Uncaught Error: Module build failed: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (F:\react-master\react-master\node_modules\@babel\helper-module-imports\lib\index.js:23:46)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (F:\react-master\react-master\node_modules\babel-plugin-import\lib\Plugin.js:10:28)
    at Module._compile (module.js:413:34)
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (F:\react-master\react-master\node_modules\@babel\helper-module-imports\lib\index.js:23:46)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (F:\react-master\react-master\node_modules\babel-plugin-import\lib\Plugin.js:10:28)
    at Module._compile (module.js:413:34)
    at Object.25 (http://localhost:3010/client.115f.js:39:7)
    at __webpack_require__ (http://localhost:3010/common.bundle.js:55:30)
    at Object.2 (http://localhost:3010/client.115f.js:7:18)
    at __webpack_require__ (http://localhost:3010/common.bundle.js:55:30)
    at webpackJsonpCallback (http://localhost:3010/common.bundle.js:26:23)
    at http://localhost:3010/client.115f.js:1:1

**Comment by duxianwei520** [comment]
最近两个月没有有更新这个项目了，应该不会又这样的情况，要不你重新npm install之后再试试，可能有些依赖包没有下载下来

**Comment by duxianwei520** [comment]
@zhangxu003 是没有这个问题的吧，大概率是你的网络问题导致有些包没下载完全，我多次测试都没这问题

**Comment by zhangxu003** [comment]
嗯嗯  是的 我更新了node 和 npm  版本就好了 谢谢你
